# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190523_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
