# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-published_date']},
        ),
    ]
