# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateTimeField(blank=True, default='May 25, 2019, 8:59 a.m.', null=True),
        ),
    ]
