# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190525_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
