# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190623_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
