# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
