# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190620_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='../static/img/profile_images/male_def.png', upload_to='profile_images'),
        ),
    ]
