# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190623_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
