# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190623_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='user_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
