# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190623_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_gender',
            new_name='gender',
        ),
    ]
