# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_available_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=60)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('open', models.BooleanField(default=True)),
                ('upvotes', models.PositiveSmallIntegerField(default=0)),
                ('needed_upvotes', models.PositiveIntegerField(default=50)),
                ('slug', models.SlugField(unique=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('upvoted_by', models.ManyToManyField(blank=True, related_name='feature_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
