# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='needed_upvotes',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
