# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190912_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='open',
            field=models.CharField(choices=[('O', 'Opened'), ('D', 'Under Development'), ('C', 'Closed')], default=('O', 'Opened'), max_length=1),
        ),
    ]
