# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_available_upvotes'),
        ('features', '0004_remove_feature_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='feature',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_likes', to='accounts.UserProfile'),
        ),
    ]
