# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20190912_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
