# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0006_auto_20190827_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='feature_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='feature',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
