# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190912_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
