# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20190912_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='open',
            field=models.CharField(choices=[('O', 'Opened'), ('D', 'Under Development'), ('C', 'Closed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
