# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190912_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='open',
            field=models.CharField(choices=[(1, 'Opened'), (2, 'Under Development'), (3, 'Closed')], default=1, max_length=1),
        ),
    ]
