# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0017_auto_20190913_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='open',
            field=models.CharField(choices=[('OP', 'Open'), ('UD', 'Under Development'), ('CL', 'Closed')], default='OP', max_length=11),
        ),
    ]
