# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20190913_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='open',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Under Development'), ('2', 'Closed')], default='0', max_length=11),
        ),
    ]
