# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-upvotes']},
        ),
    ]
