# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
