# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190711_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bugs_images')),
                ('bug', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bugs.Bug')),
            ],
        ),
    ]
