# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190624_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
