# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bugimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugImage',
            new_name='Images',
        ),
    ]
