# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20190712_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='BugImages',
        ),
    ]
