# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190712_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='bug',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
