# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20190801_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-upvotes', '-published_date']},
        ),
    ]
