# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20190625_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='comments',
        ),
    ]
