# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_remove_bug_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='views',
        ),
    ]
