# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0008_auto_20190811_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='bug',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='bug',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='bug_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
