# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20190820_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={},
        ),
    ]
